export const Translations = {
  en: {
    // Tabs
    tab_home: "Home",
    tab_explore: "Explore",
    tab_rewards: "Rewards",
    tab_referral: "Referral",
    tab_user: "User",

    // Home Tab
    mining_active: "Mining Active",
    start_mining: "Start Mining",
    boost_mining: "Boost Mining",
    boost_desc: "Watch an ad to boost mining rate by 2x for 30 minutes!",
    beta_live: "Lassan Network Beta Live (Early Phase)",
    beta_desc: "Be a pioneer in the Web3 revolution! Secure your LSN tokens early and power the decentralized Lassan Network.",
    claim_daily_bonus: "Claim Daily Bonus",
    bonus_claimed_msg: "Daily Bonus Claimed",
    already_claimed_msg: "You have already claimed your daily bonus. Come back tomorrow!",
    success: "Success",
    daily_bonus: "Daily Bonus",
    weekly_bonus: "Weekly Bonus",
    btn_bonus: "BONUS",
    btn_boost: "BOOST",
    referral: "Referral",
    social_tasks: "Social Tasks",
    airdrop_eligibility: "Airdrop Eligibility",
    airdrop_desc: "Complete all social tasks and maintain a 7-day mining streak to be eligible for the upcoming Lassan Airdrop. Stay tuned for more updates!",
    
    // Referral Tab
    my_referrals_team: "My Referrals Team",
    invite_friends: "Invite Friends",
    share_code_desc: "Share your code with friends and earn 10% of their mining rate forever!",
    your_referral_code: "Your Referral Code",
    copy: "Copy",
    total_referrals: "Total Referrals",
    active_miners: "Active Miners",
    inactive: "Inactive",
    notify: "Notify",
    remind: "Remind",
    notification_sent: "Notification Sent",
    base_rate: "Base Rate",
    referral_boost: "Referral Boost",
    mining_rate: "Mining Rate",
    referrer_family: "Referrer Family",
    no_referrals: "No referrals yet",
    active: "Active",
    
    // Rewards Tab
    rewards_title: "REWARDS",
    daily_login: "Daily Login",
    claim: "Claim",
    claimed: "Claimed",
    weekly_streak: "Weekly Streak",
    daily_streak: "Daily Streak",
    streak_desc: "Keep mining to earn Weekly Bonus",
    day: "Day",
    complete_task: "Complete Task",
    task_desc: "Did you complete this task?",
    yes: "Yes",
    no: "No",
    reward_claimed: "Reward Claimed",
    
    // Explore Tab
    explore_title: "Explore Lassan",
    featured_news: "Featured News",
    read_more: "Read More",
    trending: "Trending",
    network_stats: "Network Stats",
    recent_updates: "Recent Updates",
    total_miners: "Total Miners",
    global_hashrate: "Global Hashrate",
    lsn_mined: "LSN Mined",
    nodes_active: "Nodes Active",
    
    // User Tab
    user_settings: "USER SETTINGS",
    kyc_pending: "KYC Pending",
    coming_soon: "Coming Soon",
    
    // Menu Options
    menu_personal_info: "Personal Information",
    menu_personal_info_sub: "Edit your details",
    menu_security: "Security & Privacy",
    menu_security_sub: "2FA, Password",
    menu_wallet: "Wallet Settings",
    menu_wallet_sub: "Manage addresses",
    menu_language: "Language",
    menu_language_sub: "English (US)",
    menu_help: "Help & Support",
    menu_help_sub: "FAQs, Contact Us",
    
    // Actions
    logout: "Log Out",
    version: "Version",
    
    // Alerts
    feature_phase_3: "This feature will be available in Phase 3.",
    feature_next_update: "This feature will be available in the next update.",

    // Help & Support
    contact_support: "Contact Support",
    faq_title: "Frequently Asked Questions",
    faq_mining_q: "How does mining work?",
    faq_mining_a: "Mining in Lassan is simulated. You earn LSN tokens by activating the mining session every 24 hours.",
    faq_kyc_q: "When will KYC be available?",
    faq_kyc_a: "KYC verification is scheduled for Phase 3 of our roadmap. Stay tuned for announcements.",
    faq_referral_q: "How do referrals work?",
    faq_referral_a: "You earn a 10% permanent boost to your mining rate for every active user you refer.",
    faq_wallet_q: "Can I withdraw my tokens?",
    faq_wallet_a: "Withdrawals will be enabled after the Mainnet launch. Currently, tokens are in a testnet phase.",
    faq_privacy_q: "Is my data safe?",
    faq_privacy_a: "We prioritize your privacy. We do not sell your personal data. Your information is encrypted and used solely for account verification and network security.",
    faq_register_q: "I can't register or login?",
    faq_register_a: "Ensure you have a stable internet connection. If the issue persists, try clearing your app cache or contact our support team via Telegram.",
    faq_value_q: "What is the value of LSN?",
    faq_value_a: "LSN is currently in the mining phase. Its market value will be determined by supply and demand after listing on exchanges.",
    faq_multiple_q: "Can I have multiple accounts?",
    faq_multiple_a: "No, multiple accounts are strictly prohibited. Our anti-fraud system will ban accounts found violating this rule to ensure fair distribution.",
    
    // Language Selection
    select_language: "Select Language",
    cancel: "Cancel"
  },
  hi: {
    tab_home: "होम",
    tab_explore: "एक्सप्लोर",
    tab_rewards: "इनाम",
    tab_referral: "रेफरल",
    tab_user: "प्रोफाइल",
    mining_active: "माइनिंग सक्रिय",
    start_mining: "माइनिंग शुरू करें",
    boost_mining: "माइनिंग बूस्ट",
    boost_desc: "30 मिनट के लिए खनन दर को 2x बढ़ाने के लिए एक विज्ञापन देखें!",
    beta_live: "लस्सन नेटवर्क बीटा लाइव (प्रारंभिक चरण)",
    beta_desc: "Web3 क्रांति में अग्रणी बनें! अपने LSN टोकन जल्दी सुरक्षित करें और विकेंद्रीकृत लस्सन नेटवर्क को शक्ति प्रदान करें।",
    claim_daily_bonus: "दैनिक बोनस का दावा करें",
    bonus_claimed_msg: "दैनिक बोनस का दावा किया गया",
    already_claimed_msg: "आपने पहले ही अपने दैनिक बोनस का दावा कर लिया है। कल वापस आएं!",
    success: "सफलता",
    daily_bonus: "दैनिक बोनस",
    weekly_bonus: "साप्ताहिक बोनस",
    btn_bonus: "बोनस",
    btn_boost: "बूस्ट",
    referral: "रेफरल",
    social_tasks: "सामाजिक कार्य",
    airdrop_eligibility: "एयरड्रॉप पात्रता",
    airdrop_desc: "आगामी लस्सन एयरड्रॉप के लिए पात्र होने के लिए सभी सामाजिक कार्यों को पूरा करें और 7-दिवसीय माइनिंग स्ट्रीक बनाए रखें। अधिक अपडेट के लिए बने रहें!",
    my_referrals_team: "मेरी रेफरल टीम",
    invite_friends: "दोस्तों को आमंत्रित करें",
    share_code_desc: "अपने दोस्तों के साथ अपना कोड साझा करें और उनकी माइनिंग दर का 10% हमेशा के लिए कमाएं!",
    your_referral_code: "आपका रेफरल कोड",
    copy: "कॉपी",
    total_referrals: "कुल रेफरल",
    active_miners: "सक्रिय माइनर्स",
    inactive: "निष्क्रिय",
    notify: "सूचित करें",
    remind: "याद दिलाएं",
    notification_sent: "अधिसूचना भेजी गई",
    base_rate: "आधार दर",
    referral_boost: "रेफरल बूस्ट",
    mining_rate: "माइनिंग दर",
    referrer_family: "रेफरर परिवार",
    no_referrals: "कोई रेफरल नहीं",
    active: "सक्रिय",
    rewards_title: "इनाम",
    daily_login: "दैनिक लॉगिन",
    claim: "दावा करें",
    claimed: "दावा किया",
    weekly_streak: "साप्ताहिक स्ट्रीक",
    daily_streak: "दैनिक स्ट्रीक",
    streak_desc: "साप्ताहिक बोनस कमाने के लिए माइनिंग जारी रखें",
    day: "दिन",
    complete_task: "कार्य पूरा करें",
    task_desc: "क्या आपने यह कार्य पूरा किया?",
    yes: "हाँ",
    no: "नहीं",
    reward_claimed: "इनाम का दावा किया गया",
    explore_title: "लस्सन एक्सप्लोर करें",
    featured_news: "प्रमुख समाचार",
    read_more: "और पढ़ें",
    trending: "ट्रेंडिंग",
    network_stats: "नेटवर्क आँकड़े",
    recent_updates: "हाल के अपडेट",
    total_miners: "कुल माइनर्स",
    global_hashrate: "ग्लोबल हैशरेट",
    lsn_mined: "LSN माइन किया गया",
    nodes_active: "सक्रिय नोड्स",
    user_settings: "उपयोगकर्ता सेटिंग्स",
    kyc_pending: "KYC लंबित",
    coming_soon: "जल्द आ रहा है",
    menu_personal_info: "व्यक्तिगत जानकारी",
    menu_personal_info_sub: "विवरण संपादित करें",
    menu_security: "सुरक्षा और गोपनीयता",
    menu_security_sub: "2FA, पासवर्ड",
    menu_wallet: "वॉलेट सेटिंग्स",
    menu_wallet_sub: "पते प्रबंधित करें",
    menu_language: "भाषा (Language)",
    menu_language_sub: "हिंदी (Hindi)",
    menu_help: "सहायता और समर्थन",
    menu_help_sub: "FAQs, संपर्क करें",
    logout: "लॉग आउट",
    version: "संस्करण",
    feature_phase_3: "यह सुविधा चरण 3 में उपलब्ध होगी।",
    feature_next_update: "यह सुविधा अगले अपडेट में उपलब्ध होगी।",

    // Help & Support
    contact_support: "समर्थन से संपर्क करें",
    faq_title: "अक्सर पूछे जाने वाले प्रश्न",
    faq_mining_q: "माइनिंग कैसे काम करती है?",
    faq_mining_a: "लस्सन में माइनिंग सिम्युलेटेड है। आप हर 24 घंटे में माइनिंग सत्र सक्रिय करके LSN टोकन कमाते हैं।",
    faq_kyc_q: "KYC कब उपलब्ध होगा?",
    faq_kyc_a: "KYC सत्यापन हमारे रोडमैप के चरण 3 के लिए निर्धारित है। घोषणाओं के लिए बने रहें।",
    faq_referral_q: "रेफरल कैसे काम करते हैं?",
    faq_referral_a: "आप अपने द्वारा रेफर किए गए प्रत्येक सक्रिय उपयोगकर्ता के लिए अपनी माइनिंग दर में 10% स्थायी बूस्ट कमाते हैं।",
    faq_wallet_q: "क्या मैं अपने टोकन निकाल सकता हूँ?",
    faq_wallet_a: "मेननेट लॉन्च के बाद निकासी सक्षम की जाएगी। वर्तमान में, टोकन टेस्टनेट चरण में हैं।",
    faq_privacy_q: "क्या मेरा डेटा सुरक्षित है?",
    faq_privacy_a: "हम आपकी गोपनीयता को प्राथमिकता देते हैं। हम आपका व्यक्तिगत डेटा नहीं बेचते हैं। आपकी जानकारी एन्क्रिप्टेड है और केवल खाता सत्यापन और नेटवर्क सुरक्षा के लिए उपयोग की जाती है।",
    faq_register_q: "मैं पंजीकरण या लॉगिन नहीं कर पा रहा हूँ?",
    faq_register_a: "सुनिश्चित करें कि आपके पास एक स्थिर इंटरनेट कनेक्शन है। यदि समस्या बनी रहती है, तो अपना ऐप कैश साफ़ करने का प्रयास करें या टेलीग्राम के माध्यम से हमारी सहायता टीम से संपर्क करें।",
    faq_value_q: "LSN का मूल्य क्या है?",
    faq_value_a: "LSN वर्तमान में माइनिंग चरण में है। इसका बाजार मूल्य एक्सचेंजों पर लिस्टिंग के बाद आपूर्ति और मांग द्वारा निर्धारित किया जाएगा।",
    faq_multiple_q: "क्या मेरे पास कई खाते हो सकते हैं?",
    faq_multiple_a: "नहीं, कई खाते रखना सख्त मना है। हमारा एंटी-फ्रॉड सिस्टम निष्पक्ष वितरण सुनिश्चित करने के लिए इस नियम का उल्लंघन करने वाले खातों को प्रतिबंधित कर देगा।",

    select_language: "भाषा चुनें",
    cancel: "रद्द करें"
  },
  es: {
    tab_home: "Inicio",
    tab_explore: "Explorar",
    tab_rewards: "Recompensas",
    tab_referral: "Referidos",
    tab_user: "Usuario",
    mining_active: "Minería Activa",
    start_mining: "Iniciar Minería",
    boost_mining: "Impulsar Minería",
    boost_desc: "¡Mira un anuncio para aumentar la tasa de minería en 2x durante 30 minutos!",
    beta_live: "Lassan Network Beta en Vivo",
    beta_desc: "Únete a la revolución del enrutamiento de cebolla descentralizado.",
    claim_daily_bonus: "Reclamar Bono Diario",
    bonus_claimed_msg: "Bono Diario Reclamado",
    already_claimed_msg: "Ya has reclamado tu bono diario. ¡Vuelve mañana!",
    success: "Éxito",
    daily_bonus: "Bono Diario",
    weekly_bonus: "Bono Semanal",
    btn_bonus: "BONO",
    btn_boost: "IMPULSO",
    referral: "Referidos",
    social_tasks: "Tareas Sociales",
    airdrop_eligibility: "Elegibilidad Airdrop",
    airdrop_desc: "¡Complete todas las tareas sociales y mantenga una racha de minería de 7 días para ser elegible para el próximo Airdrop de Lassan!",
    my_referrals_team: "Mi Equipo",
    invite_friends: "Invitar Amigos",
    share_code_desc: "¡Comparte tu código con amigos y gana el 10% de su tasa de minería para siempre!",
    your_referral_code: "Tu Código",
    copy: "Copiar",
    total_referrals: "Total Referidos",
    active_miners: "Mineros Activos",
    inactive: "Inactivo",
    notify: "Notificar",
    remind: "Recordar",
    notification_sent: "Notificación Enviada",
    base_rate: "Tasa Base",
    referral_boost: "Impulso Referido",
    mining_rate: "Tasa Minería",
    referrer_family: "Familia Referente",
    no_referrals: "Sin referidos",
    active: "Activo",
    rewards_title: "RECOMPENSAS",
    daily_login: "Inicio Diario",
    claim: "Reclamar",
    claimed: "Reclamado",
    weekly_streak: "Racha Semanal",
    daily_streak: "Racha Diaria",
    streak_desc: "Sigue minando para ganar el Bono Semanal",
    day: "Día",
    complete_task: "Completar Tarea",
    task_desc: "¿Completaste esta tarea?",
    yes: "Sí",
    no: "No",
    reward_claimed: "Recompensa Reclamada",
    explore_title: "Explorar Lassan",
    featured_news: "Noticias Destacadas",
    read_more: "Leer Más",
    trending: "Tendencias",
    network_stats: "Estadísticas de Red",
    recent_updates: "Actualizaciones Recientes",
    total_miners: "Mineros Totales",
    global_hashrate: "Hashrate Global",
    lsn_mined: "LSN Minado",
    nodes_active: "Nodos Activos",
    user_settings: "AJUSTES DE USUARIO",
    kyc_pending: "KYC Pendiente",
    coming_soon: "Próximamente",
    menu_personal_info: "Información Personal",
    menu_personal_info_sub: "Editar detalles",
    menu_security: "Seguridad y Privacidad",
    menu_security_sub: "2FA, Contraseña",
    menu_wallet: "Ajustes de Billetera",
    menu_wallet_sub: "Gestionar direcciones",
    menu_language: "Idioma (Language)",
    menu_language_sub: "Español",
    menu_help: "Ayuda y Soporte",
    menu_help_sub: "Preguntas frecuentes",
    logout: "Cerrar Sesión",
    version: "Versión",
    feature_phase_3: "Esta función estará disponible en la Fase 3.",
    feature_next_update: "Esta función estará disponible en la próxima actualización.",
    select_language: "Seleccionar Idioma",
    cancel: "Cancelar"
  },
  fr: {
    tab_home: "Accueil",
    tab_explore: "Explorer",
    tab_rewards: "Récompenses",
    tab_referral: "Parrainage",
    tab_user: "Profil",
    mining_active: "Minage Actif",
    start_mining: "Lancer Minage",
    boost_mining: "Booster Minage",
    boost_desc: "Regardez une publicité pour augmenter le taux de minage de 2x pendant 30 minutes !",
    beta_live: "Lassan Network Beta en Direct",
    beta_desc: "Rejoignez la révolution du routage en oignon décentralisé.",
    claim_daily_bonus: "Réclamer Bonus Quotidien",
    bonus_claimed_msg: "Bonus Quotidien Réclamé",
    already_claimed_msg: "Vous avez déjà réclamé votre bonus quotidien. Revenez demain !",
    success: "Succès",
    daily_bonus: "Bonus Quotidien",
    weekly_bonus: "Bonus Hebdo",
    btn_bonus: "BONUS",
    btn_boost: "BOOST",
    referral: "Parrainage",
    social_tasks: "Tâches Sociales",
    airdrop_eligibility: "Éligibilité Airdrop",
    airdrop_desc: "Complétez toutes les tâches sociales et maintenez une série de minage de 7 jours pour être éligible au prochain Airdrop Lassan !",
    my_referrals_team: "Mon Équipe",
    invite_friends: "Inviter Amis",
    share_code_desc: "Partagez votre code et gagnez 10% de leur taux de minage pour toujours !",
    your_referral_code: "Votre Code",
    copy: "Copier",
    total_referrals: "Total Parrainages",
    active_miners: "Mineurs Actifs",
    inactive: "Inactif",
    notify: "Notifier",
    remind: "Rappeler",
    notification_sent: "Notification Envoyée",
    base_rate: "Taux Base",
    referral_boost: "Boost Parrainage",
    mining_rate: "Taux Minage",
    referrer_family: "Famille Parrain",
    no_referrals: "Aucun parrainage",
    active: "Actif",
    rewards_title: "RÉCOMPENSES",
    daily_login: "Connexion Quotidienne",
    claim: "Réclamer",
    claimed: "Réclamé",
    weekly_streak: "Série Hebdo",
    daily_streak: "Série Quotidienne",
    streak_desc: "Continuez à miner pour le Bonus Hebdo",
    day: "Jour",
    complete_task: "Terminer Tâche",
    task_desc: "Avez-vous terminé cette tâche ?",
    yes: "Oui",
    no: "Non",
    reward_claimed: "Récompense Réclamée",
    explore_title: "Explorer Lassan",
    featured_news: "À la Une",
    read_more: "Lire Plus",
    trending: "Tendances",
    network_stats: "Stats Réseau",
    recent_updates: "Mises à jour Récentes",
    total_miners: "Mineurs Totaux",
    global_hashrate: "Hashrate Global",
    lsn_mined: "LSN Miné",
    nodes_active: "Nœuds Actifs",
    user_settings: "PARAMÈTRES UTILISATEUR",
    kyc_pending: "KYC En Attente",
    coming_soon: "Bientôt",
    menu_personal_info: "Infos Personnelles",
    menu_personal_info_sub: "Modifier détails",
    menu_security: "Sécurité & Vie Privée",
    menu_security_sub: "2FA, Mot de passe",
    menu_wallet: "Paramètres Portefeuille",
    menu_wallet_sub: "Gérer adresses",
    menu_language: "Langue (Language)",
    menu_language_sub: "Français",
    menu_help: "Aide & Support",
    menu_help_sub: "FAQ, Contact",
    logout: "Déconnexion",
    version: "Version",
    feature_phase_3: "Cette fonctionnalité sera disponible dans la Phase 3.",
    feature_next_update: "Cette fonctionnalité sera disponible dans la prochaine mise à jour.",
    select_language: "Choisir la Langue",
    cancel: "Annuler"
  },
  de: {
    tab_home: "Startseite",
    tab_explore: "Entdecken",
    tab_rewards: "Belohnungen",
    tab_referral: "Empfehlung",
    tab_user: "Benutzer",
    mining_active: "Mining Aktiv",
    start_mining: "Mining Starten",
    boost_mining: "Mining Boost",
    boost_desc: "Sehen Sie sich eine Anzeige an, um die Mining-Rate für 30 Minuten um das 2-fache zu erhöhen!",
    beta_live: "Lassan Netzwerk Beta Live",
    beta_desc: "Schließen Sie sich der Revolution des dezentralen Onion-Routings an.",
    claim_daily_bonus: "Täglichen Bonus beanspruchen",
    bonus_claimed_msg: "Täglicher Bonus beansprucht",
    already_claimed_msg: "Sie haben Ihren täglichen Bonus bereits beansprucht. Kommen Sie morgen wieder!",
    success: "Erfolg",
    daily_bonus: "Täglicher Bonus",
    weekly_bonus: "Wochenbonus",
    btn_bonus: "BONUS",
    btn_boost: "BOOST",
    referral: "Empfehlung",
    social_tasks: "Soziale Aufgaben",
    airdrop_eligibility: "Airdrop Berechtigung",
    airdrop_desc: "Erledigen Sie alle sozialen Aufgaben und halten Sie eine 7-tägige Mining-Serie aufrecht, um für den kommenden Lassan Airdrop berechtigt zu sein!",
    my_referrals_team: "Mein Team",
    invite_friends: "Freunde Einladen",
    share_code_desc: "Teilen Sie Ihren Code und verdienen Sie für immer 10% ihrer Mining-Rate!",
    your_referral_code: "Ihr Code",
    copy: "Kopieren",
    total_referrals: "Gesamt Empfehlungen",
    active_miners: "Aktive Miner",
    inactive: "Inaktiv",
    notify: "Benachrichtigen",
    remind: "Erinnern",
    notification_sent: "Benachrichtigung Gesendet",
    base_rate: "Basisrate",
    referral_boost: "Empfehlungs-Boost",
    mining_rate: "Mining-Rate",
    referrer_family: "Empfehler-Familie",
    no_referrals: "Keine Empfehlungen",
    active: "Aktiv",
    rewards_title: "BELOHNUNGEN",
    daily_login: "Täglicher Login",
    claim: "Beanspruchen",
    claimed: "Beansprucht",
    weekly_streak: "Wochenserie",
    daily_streak: "Tages-Serie",
    streak_desc: "Weiter minen für Wochenbonus",
    day: "Tag",
    complete_task: "Aufgabe Abschließen",
    task_desc: "Haben Sie diese Aufgabe erledigt?",
    yes: "Ja",
    no: "Nein",
    reward_claimed: "Belohnung Beansprucht",
    explore_title: "Lassan Entdecken",
    featured_news: "Top Nachrichten",
    read_more: "Mehr Lesen",
    trending: "Im Trend",
    network_stats: "Netzwerk-Statistiken",
    recent_updates: "Kürzliche Updates",
    total_miners: "Gesamt Miner",
    global_hashrate: "Globale Hashrate",
    lsn_mined: "LSN Gemint",
    nodes_active: "Aktive Knoten",
    user_settings: "BENUTZEREINSTELLUNGEN",
    kyc_pending: "KYC Ausstehend",
    coming_soon: "Demnächst",
    menu_personal_info: "Persönliche Infos",
    menu_personal_info_sub: "Details bearbeiten",
    menu_security: "Sicherheit & Datenschutz",
    menu_security_sub: "2FA, Passwort",
    menu_wallet: "Wallet Einstellungen",
    menu_wallet_sub: "Adressen verwalten",
    menu_language: "Sprache (Language)",
    menu_language_sub: "Deutsch",
    menu_help: "Hilfe & Support",
    menu_help_sub: "FAQs, Kontakt",
    logout: "Abmelden",
    version: "Version",
    feature_phase_3: "Diese Funktion wird in Phase 3 verfügbar sein.",
    feature_next_update: "Diese Funktion wird im nächsten Update verfügbar sein.",
    select_language: "Sprache Wählen",
    cancel: "Abbrechen"
  },
  zh: {
    tab_home: "首页",
    tab_explore: "探索",
    tab_rewards: "奖励",
    tab_referral: "推荐",
    tab_user: "用户",
    mining_active: "挖矿进行中",
    start_mining: "开始挖矿",
    boost_mining: "加速挖矿",
    boost_desc: "观看广告可在 30 分钟内将挖矿率提高 2 倍！",
    beta_live: "Lassan 网络测试版上线",
    beta_desc: "加入去中心化洋葱路由的革命。",
    claim_daily_bonus: "领取每日奖励",
    bonus_claimed_msg: "每日奖励已领取",
    already_claimed_msg: "您已领取每日奖励。请明天再来！",
    success: "成功",
    daily_bonus: "每日奖励",
    weekly_bonus: "每周奖励",
    btn_bonus: "奖励",
    btn_boost: "加速",
    referral: "推荐",
    social_tasks: "社交任务",
    airdrop_eligibility: "空投资格",
    airdrop_desc: "完成所有社交任务并保持7天连续挖矿，即可获得即将到来的Lassan空投资格！",
    my_referrals_team: "我的团队",
    invite_friends: "邀请好友",
    share_code_desc: "分享您的代码，永久赚取好友挖矿率的10%！",
    your_referral_code: "您的推荐码",
    copy: "复制",
    total_referrals: "总推荐",
    active_miners: "活跃矿工",
    inactive: "不活跃",
    notify: "通知",
    remind: "提醒",
    notification_sent: "通知已发送",
    base_rate: "基础率",
    referral_boost: "推荐加速",
    mining_rate: "挖矿率",
    referrer_family: "推荐家庭",
    no_referrals: "暂无推荐",
    active: "活跃",
    rewards_title: "奖励",
    daily_login: "每日登录",
    claim: "领取",
    claimed: "已领取",
    weekly_streak: "每周连胜",
    daily_streak: "每日连胜",
    streak_desc: "继续挖矿以获得每周奖励",
    day: "天",
    complete_task: "完成任务",
    task_desc: "您完成了这项任务吗？",
    yes: "是",
    no: "否",
    reward_claimed: "奖励已领取",
    explore_title: "探索Lassan",
    featured_news: "精选新闻",
    read_more: "阅读更多",
    trending: "热门",
    network_stats: "网络统计",
    recent_updates: "最近更新",
    total_miners: "总矿工",
    global_hashrate: "全球算力",
    lsn_mined: "LSN 已挖",
    nodes_active: "活跃节点",
    user_settings: "用户设置",
    kyc_pending: "KYC 待审核",
    coming_soon: "即将推出",
    menu_personal_info: "个人信息",
    menu_personal_info_sub: "编辑详情",
    menu_security: "安全与隐私",
    menu_security_sub: "2FA, 密码",
    menu_wallet: "钱包设置",
    menu_wallet_sub: "管理地址",
    menu_language: "语言 (Language)",
    menu_language_sub: "中文 (简体)",
    menu_help: "帮助与支持",
    menu_help_sub: "常见问题, 联系我们",
    logout: "退出登录",
    version: "版本",
    feature_phase_3: "此功能将在第三阶段推出。",
    feature_next_update: "此功能将在下次更新中推出。",
    select_language: "选择语言",
    cancel: "取消"
  },
  ar: {
    tab_home: "الرئيسية",
    tab_explore: "استكشاف",
    tab_rewards: "المكافآت",
    tab_referral: "الإحالة",
    tab_user: "المستخدم",
    mining_active: "التعدين نشط",
    start_mining: "بدء التعدين",
    boost_mining: "تعزيز التعدين",
    boost_desc: "شاهد إعلانًا لزيادة معدل التعدين بمقدار 2x لمدة 30 دقيقة!",
    beta_live: "شبكة Lassan بيتا مباشرة",
    beta_desc: "انضم إلى ثورة توجيه البصل اللامركزي.",
    claim_daily_bonus: "المطالبة بالمكافأة اليومية",
    bonus_claimed_msg: "تمت المطالبة بالمكافأة اليومية",
    already_claimed_msg: "لقد طالبت بالفعل بمكافأتك اليومية. عد غدًا!",
    success: "نجاح",
    daily_bonus: "مكافأة يومية",
    weekly_bonus: "مكافأة أسبوعية",
    btn_bonus: "مكافأة",
    btn_boost: "تعزيز",
    referral: "الإحالة",
    social_tasks: "المهام الاجتماعية",
    airdrop_eligibility: "أهلية الإيردروب",
    airdrop_desc: "أكمل جميع المهام الاجتماعية وحافظ على سلسلة تعدين لمدة 7 أيام لتكون مؤهلاً للحصول على إيردروب Lassan القادم!",
    my_referrals_team: "فريقي",
    invite_friends: "دعوة الأصدقاء",
    share_code_desc: "شارك كودك مع الأصدقاء واكسب 10% من معدل تعدينهم إلى الأبد!",
    your_referral_code: "كود الإحالة الخاص بك",
    copy: "نسخ",
    total_referrals: "إجمالي الإحالات",
    active_miners: "المعدنون النشطون",
    inactive: "غير نشط",
    notify: "إشعار",
    remind: "تذكير",
    notification_sent: "تم إرسال الإشعار",
    base_rate: "المعدل الأساسي",
    referral_boost: "تعزيز الإحالة",
    mining_rate: "معدل التعدين",
    referrer_family: "عائلة الإحالة",
    no_referrals: "لا توجد إحالات",
    active: "نشط",
    rewards_title: "المكافآت",
    daily_login: "تسجيل الدخول اليومي",
    claim: "مطالبة",
    claimed: "تمت المطالبة",
    weekly_streak: "سلسلة أسبوعية",
    daily_streak: "سلسلة يومية",
    streak_desc: "استمر في التعدين لكسب المكافأة الأسبوعية",
    day: "يوم",
    complete_task: "إكمال المهمة",
    task_desc: "هل أكملت هذه المهمة؟",
    yes: "نعم",
    no: "لا",
    reward_claimed: "تمت المطالبة بالمكافأة",
    explore_title: "استكشاف Lassan",
    featured_news: "أخبار مميزة",
    read_more: "اقرأ المزيد",
    trending: "شائع",
    network_stats: "إحصائيات الشبكة",
    recent_updates: "التحديثات الأخيرة",
    total_miners: "إجمالي المعدنين",
    global_hashrate: "معدل التجزئة العالمي",
    lsn_mined: "LSN المعدنة",
    nodes_active: "العقد النشطة",
    user_settings: "إعدادات المستخدم",
    kyc_pending: "KYC معلق",
    coming_soon: "قريباً",
    menu_personal_info: "المعلومات الشخصية",
    menu_personal_info_sub: "تعديل التفاصيل",
    menu_security: "الأمان والخصوصية",
    menu_security_sub: "2FA, كلمة المرور",
    menu_wallet: "إعدادات المحفظة",
    menu_wallet_sub: "إدارة العناوين",
    menu_language: "اللغة (Language)",
    menu_language_sub: "العربية",
    menu_help: "المساعدة والدعم",
    menu_help_sub: "الأسئلة الشائعة, اتصل بنا",
    logout: "تسجيل الخروج",
    version: "الإصدار",
    feature_phase_3: "ستتوفر هذه الميزة في المرحلة 3.",
    feature_next_update: "ستتوفر هذه الميزة في التحديث القادم.",
    select_language: "اختر اللغة",
    cancel: "إلغاء"
  }
};
